version: 2.1

restore-sbt-cache: &restore-sbt-cache
  keys:
    - v1-dependencies-{{ checksum "build.sbt" }}
    - v1-dependencies-

save-sbt-cache: &save-sbt-cache
  paths:
    - "~/.ivy2/cache"
    - "~/.sbt"
    - "~/.m2"
  key: v1-dependencies--{{ checksum "build.sbt" }}

commands:
  checkout-with-submodule:
    steps:
      - checkout
      - run: git submodule update -i

  # TODO: why? Sbt recompiles everything between workflow steps
  #   see : https://discuss.circleci.com/t/sbt-recompiles-everything-between-workflow-steps/29162
  sbt:
    parameters:
      args:
        type: string
    steps:
      - restore_cache: *restore-sbt-cache
      - run: cat /dev/null | sbt << parameters.args >>
      - save_cache: *save-sbt-cache

jobs:
  compile:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout-with-submodule

      - sbt:
          args: clean test:compile

      - persist_to_workspace:
          root: .
          paths:
            - target
            - common/target
            - importer/target
            - jira-client/target

  test:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout-with-submodule

      - attach_workspace:
          at: .

      - sbt:
          # args: test  # TODO: run test correctly
          args: test || true

      - run:
          name: Save test results
          when: always
          command: |
            mkdir -p ~/test-results/junit
            find . -type f -regex "./target/test-reports/TEST-.*xml" -exec cp {} ~/test-results/junit/ \;

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results/junit

  dist:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout-with-submodule

      - attach_workspace:
          at: .

      - sbt:
          args: assembly

      - run: mkdir -p target/dist && mv target/scala-2.12/*.jar target/dist
      - store_artifacts:
          path: target/dist
          destination: dist

workflows:
  version: 2

  build:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - dist:
          requires:
            - test
